spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.124:3306/platform?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Y~ouTu^MYSQL$2016
  redis:
    database: 0
    host: 192.168.1.124
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8899
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:sqlMappers/*.xml